#!/usr/bin/env python3
"""Generate the standalone Codex skill from the Claude Code workflow."""

import argparse
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "plugins/rn-upgrade/skills/apply-upgrade-diff/SKILL.md"
DESTINATION = ROOT / "skills/apply-upgrade-diff/SKILL.md"
CLAUDE_INPUTS = """Arguments: `$ARGUMENTS` — in order: TARGET_VERSION, APP_ROOT, FROM_VERSION.
(Pasting this prompt into another tool? Replace the arguments line with the values below. You may
also add REPORT_PATH, a file outside the repo to save the report to.)"""
CODEX_INPUTS = """Read TARGET_VERSION, APP_ROOT, and optional FROM_VERSION from the user's request, either as
`KEY=VALUE` pairs (`$apply-upgrade-diff TARGET_VERSION=0.86.3 APP_ROOT=.`) or positionally in that
order (`$apply-upgrade-diff 0.86.3 .`). The user may also provide REPORT_PATH, a file outside the
app's repo to save the report to.
Follow this workflow exactly, stay inside its scope, and back every claim in your report with
evidence (file:line, commit SHA, command output)."""
# Text that only makes sense inside Claude Code and must never reach the Codex skill.
CLAUDE_ONLY = ("$ARGUMENTS", "rn-upgrade:", "context: fork", "agent:", "argument-hint")


def render():
    source = SOURCE.read_text(encoding="utf-8")
    parts = source.split("---\n", 2)
    if len(parts) != 3 or parts[0]:
        raise ValueError(f"{SOURCE.relative_to(ROOT)} must start with a --- frontmatter block.")
    _, frontmatter, body = parts
    for line in frontmatter.splitlines():
        if line[:1].isspace() or line.rstrip().endswith(("|", ">", "|-", ">-", "|+", ">+")):
            raise ValueError("Multi-line frontmatter values are not supported; keep each value on one line.")
    # Keep the portable metadata; Claude's fork, agent and arguments are host-specific.
    metadata = [line for line in frontmatter.splitlines() if line.startswith(("name:", "description:"))]
    if len(metadata) != 2 or body.count(CLAUDE_INPUTS) != 1:
        raise ValueError("Source structure changed; update the Codex adapter before generating.")
    body = body.replace(CLAUDE_INPUTS, CODEX_INPUTS)
    leftovers = [token for token in CLAUDE_ONLY if token in body]
    if leftovers:
        raise ValueError(f"Claude-specific text left in the Codex skill: {leftovers}")
    note = (
        "\n<!-- Generated by scripts/sync-codex-skill.py from "
        f"{SOURCE.relative_to(ROOT)}. Edit that file, not this one. -->\n"
    )
    return "---\n" + "\n".join(metadata) + "\n---\n" + note + body


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Fail if the generated skill is stale")
    args = parser.parse_args()
    try:
        expected = render()
    except ValueError as error:
        sys.exit(f"error: {error}")
    if args.check:
        if not DESTINATION.exists() or DESTINATION.read_text(encoding="utf-8") != expected:
            parser.exit(1, "Codex skill is stale. Run python3 scripts/sync-codex-skill.py\n")
        print("Codex skill is up to date.")
    else:
        DESTINATION.parent.mkdir(parents=True, exist_ok=True)
        DESTINATION.write_text(expected, encoding="utf-8", newline="\n")
        print(f"Generated {DESTINATION.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
