#!/usr/bin/env python3
"""Generate the standalone Codex skill from the Claude Code workflow."""

import argparse
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "plugins/rn-upgrade/skills/apply-upgrade-diff/SKILL.md"
DESTINATION = ROOT / "skills/apply-upgrade-diff/SKILL.md"
CLAUDE_INPUTS = """Arguments: `$ARGUMENTS` — in order: TARGET_VERSION, APP_ROOT, FROM_VERSION.
(Pasting this prompt into another tool? Replace the arguments line with the values below. You may
also add REPORT_PATH, a file outside the repo to save the report to.)"""
CODEX_INPUTS = """Read TARGET_VERSION, APP_ROOT, and optional FROM_VERSION from the user's request.
For example: `$apply-upgrade-diff TARGET_VERSION=0.86.3 APP_ROOT=.`
The user may also provide REPORT_PATH, a file outside the app's repo to save the report to.
Run the workflow in the current Codex session; no dedicated subagent or model is required."""


def render():
    source = SOURCE.read_text(encoding="utf-8")
    _, frontmatter, body = source.split("---\n", 2)
    # Keep the portable metadata; Claude's fork, agent and arguments are host-specific.
    metadata = [
        line for line in frontmatter.splitlines()
        if line.startswith(("name:", "description:"))
    ]
    if len(metadata) != 2 or body.count(CLAUDE_INPUTS) != 1:
        raise ValueError("Source structure changed; update the Codex adapter before generating.")
    body = body.replace(CLAUDE_INPUTS, CODEX_INPUTS)
    note = "\n<!-- Generated by scripts/sync-codex-skill.py; edit the source workflow instead. -->\n"
    return "---\n" + "\n".join(metadata) + "\n---\n" + note + body


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Fail if the generated skill is stale")
    args = parser.parse_args()
    expected = render()
    if args.check:
        if not DESTINATION.exists() or DESTINATION.read_text(encoding="utf-8") != expected:
            parser.exit(1, "Codex skill is stale. Run python3 scripts/sync-codex-skill.py\n")
        print("Codex skill is up to date.")
    else:
        DESTINATION.parent.mkdir(parents=True, exist_ok=True)
        DESTINATION.write_text(expected, encoding="utf-8")
        print(f"Generated {DESTINATION.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
