#!/usr/bin/env python3
"""Generate the standalone Codex skills from the Claude Code workflows."""

import argparse
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE_DIR = ROOT / "plugins/rn-upgrade/skills"
DESTINATION_DIR = ROOT / "skills"
CLAUDE_INPUTS = """Arguments: `$ARGUMENTS` — in order: TARGET_VERSION, APP_ROOT, FROM_VERSION.
(Pasting this prompt into another tool? Replace the arguments line with the values below. You may
also add REPORT_PATH, a file outside the repo to save the report to, and HTML=no to skip the HTML
page saved next to it.)"""
CODEX_INPUTS = """Read TARGET_VERSION, APP_ROOT, and optional FROM_VERSION from the user's request, either as
`KEY=VALUE` pairs (`{invocation} TARGET_VERSION=0.86.3 APP_ROOT=.`) or positionally in that
order (`{invocation} 0.86.3 .`). The user may also provide REPORT_PATH, a file outside the
app's repo to save the report to, and HTML=no to skip the HTML page saved next to it.
Follow this workflow exactly, stay inside its scope, and back every claim in your report with
evidence (file:line, commit SHA, command output)."""
SKILL_DIR_NOTE = """
`<SKILL_DIR>` below is the folder that contains this SKILL.md, not the current directory. Resolve
it to an absolute path before running anything from it."""
# Text that only makes sense inside Claude Code and must never reach the Codex skill.
CLAUDE_ONLY = ("$ARGUMENTS", "rn-upgrade:", "context: fork", "agent:", "argument-hint", "CLAUDE_SKILL_DIR")


def render(source_path):
    source = source_path.read_text(encoding="utf-8")
    name = source_path.parent.name
    parts = source.split("---\n", 2)
    if len(parts) != 3 or parts[0]:
        raise ValueError(f"{source_path.relative_to(ROOT)} must start with a --- frontmatter block.")
    _, frontmatter, body = parts
    for line in frontmatter.splitlines():
        if line[:1].isspace() or line.rstrip().endswith(("|", ">", "|-", ">-", "|+", ">+")):
            raise ValueError("Multi-line frontmatter values are not supported; keep each value on one line.")
    # Keep the portable metadata; Claude's fork, agent and arguments are host-specific.
    metadata = [line for line in frontmatter.splitlines() if line.startswith(("name:", "description:"))]
    if len(metadata) != 2 or body.count(CLAUDE_INPUTS) != 1:
        raise ValueError(f"{name}: source structure changed; update the Codex adapter before generating.")
    codex_inputs = CODEX_INPUTS.format(invocation=f"${name}")
    if "${CLAUDE_SKILL_DIR}" in body:
        codex_inputs += SKILL_DIR_NOTE
        body = body.replace("${CLAUDE_SKILL_DIR}", "<SKILL_DIR>")
    body = body.replace(CLAUDE_INPUTS, codex_inputs)
    leftovers = [token for token in CLAUDE_ONLY if token in body]
    if leftovers:
        raise ValueError(f"{name}: Claude-specific text left in the Codex skill: {leftovers}")
    note = (
        "\n<!-- Generated by scripts/sync-codex-skill.py from "
        f"{source_path.relative_to(ROOT)}. Edit that file, not this one. -->\n"
    )
    return "---\n" + "\n".join(metadata) + "\n---\n" + note + body


def expected_files():
    """Map every generated path to its expected bytes."""
    files = {}
    for source_path in sorted(SOURCE_DIR.glob("*/SKILL.md")):
        skill = source_path.parent
        destination = DESTINATION_DIR / skill.name
        files[destination / "SKILL.md"] = render(source_path).encode("utf-8")
        scripts = skill / "scripts"
        for path in sorted(scripts.rglob("*")) if scripts.is_dir() else []:
            if path.is_file():
                files[destination / path.relative_to(skill)] = path.read_bytes()
    return files


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Fail if a generated skill is stale")
    args = parser.parse_args()
    try:
        expected = expected_files()
    except ValueError as error:
        sys.exit(f"error: {error}")
    # Files in a generated skill folder that no source produces any more.
    skills = {path.relative_to(DESTINATION_DIR).parts[0] for path in expected}
    extra = [
        path for skill in sorted(skills) if (DESTINATION_DIR / skill).is_dir()
        for path in sorted((DESTINATION_DIR / skill).rglob("*")) if path.is_file() and path not in expected
    ]
    if args.check:
        stale = [path for path, data in expected.items() if not path.exists() or path.read_bytes() != data]
        if stale or extra:
            for path in stale + extra:
                print(f"stale: {path.relative_to(ROOT)}", file=sys.stderr)
            parser.exit(1, "Codex skills are stale. Run python3 scripts/sync-codex-skill.py\n")
        print("Codex skills are up to date.")
        return
    for path, data in expected.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        if not path.exists() or path.read_bytes() != data:
            path.write_bytes(data)
            print(f"Generated {path.relative_to(ROOT)}")
    for path in extra:
        path.unlink()
        print(f"Removed {path.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
